// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNrkWCn7uXlCt1SHR7NnZ_CAdq1KWOmKQ',
    appId: '1:141691904005:web:28fcb4564bf5b7bdf43c6c',
    messagingSenderId: '141691904005',
    projectId: 'plantnanny-90165',
    authDomain: 'plantnanny-90165.firebaseapp.com',
    storageBucket: 'plantnanny-90165.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN6-pY3JkRqUdWyOCFc4TegtDMgcfafSY',
    appId: '1:141691904005:android:83d9ecb050adc076f43c6c',
    messagingSenderId: '141691904005',
    projectId: 'plantnanny-90165',
    storageBucket: 'plantnanny-90165.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQGMf6V5vIl0iG8sB6xE2VHT7Y1uPTSpc',
    appId: '1:141691904005:ios:b6e33f6451b4919cf43c6c',
    messagingSenderId: '141691904005',
    projectId: 'plantnanny-90165',
    storageBucket: 'plantnanny-90165.firebasestorage.app',
    iosClientId: '141691904005-sv8mmhgdo85ce2o97f51735rfes27e3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantNanny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQGMf6V5vIl0iG8sB6xE2VHT7Y1uPTSpc',
    appId: '1:141691904005:ios:b6e33f6451b4919cf43c6c',
    messagingSenderId: '141691904005',
    projectId: 'plantnanny-90165',
    storageBucket: 'plantnanny-90165.firebasestorage.app',
    iosClientId: '141691904005-sv8mmhgdo85ce2o97f51735rfes27e3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantNanny',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNrkWCn7uXlCt1SHR7NnZ_CAdq1KWOmKQ',
    appId: '1:141691904005:web:bec662e5c3fadfb3f43c6c',
    messagingSenderId: '141691904005',
    projectId: 'plantnanny-90165',
    authDomain: 'plantnanny-90165.firebaseapp.com',
    storageBucket: 'plantnanny-90165.firebasestorage.app',
  );

}